---
output:
  word_document: default
  pdf_document: default
---

```{r}
geyser = scan("/Users/yichen/Desktop/STA355/a2/geyser.txt");
length(geyser)
sort_geyser = sort(geyser)
par(mfrow = c(2,2))
plot(geyser, col="red")
plot(ecdf(geyser))
lines(sort_geyser, pnorm(sort_geyser, mean(geyser), sqrt(var(geyser))))
x.norm = rnorm(1000, mean(geyser), var(geyser))
qqnorm(geyser); qqline(x.norm);
shapiro.test(geyser)
hist(geyser)
```

```{r}
bw = c(0.1, 0.15, 0.18, 0.2, 0.4, 0.6, 0.8, 1.5)
plot_density = function(bw) {
  for (i in bw){
    plot(density(geyser, bw = i))
  }
}
par(mfrow = c(3,3))
plot_density(bw)
```



```{r}
library("mixtools")
library("ggplot2")
counter1 = 1; exp1 = 0
counter2 = 1; exp2 = 0
for(i in geyser) {
  u = runif(1, 2.5,3.5)
  if(i < 3) {
    exp1[counter1] = i
    counter1 = counter1 + 1
  } else {
    exp2[counter2] = i
    counter2 = counter2 + 1
  }
}
#theta
counter1 + counter2
portion1 = (counter1-1)/length(geyser)
portion2 = (counter2-1)/length(geyser)
portion1; portion2
std1 = 0; std2 = 0
for(i in 1: counter1 - 1) {
  std1[i] = (exp1[i] - exp1.mean)^2
}
for(i in 1: counter2 - 1) {
  std2[i] = (exp2[i] - exp2.mean)^2
}
sum(std1)/(counter1 - 2)
sum(std2)/(counter2 - 1)
exp1.mean = mean(exp1); exp2.mean = mean(exp2);
exp1.mean; exp2.mean
#myNORM = rnormmix(272, lambda = c(portion1, portion2), mu = c(exp1.mean, exp2.mean), sigma = c(1,1))

```

```{r}
#use em to verify.
myEM = normalmixEM(geyser, mu = c(exp1.mean, exp2.mean),lambda = c(portion1, portion2), sigma = c(1, 1), sd.constr = c(1,1))
myEM$mu; myEM$lambda; myEM$sigma
```

```{r}
library("stats4")
install.packages("nlnm")
library("nlnm")
income = scan("/Users/yichen/Desktop/STA355/a2/incomes.txt");
n = length(income);n
pnorm(1.96, 0, 1)
head(income)
income.log = log(income)
```

```{r}
x = runif(100000, 0, 5);
hist(x, breaks = 50)
```

```{r}
normalF <- function(mu, sigma) {
  # Log of likelihood of a normal distribution
  # parvec[1] - mean
  # parvec[2] - standard deviation
  # x - set of observations. Should be initialized before MLE
  #x = -(1/2)*log(sigma) - 0.5*(1/sigma) * sum(x-mu)^2
  #x
  R = suppressWarnings(dnorm(income.log, mu, sigma))
  -sum(log(R))
}
mean(income.log); var(income.log)
normalF(1,1)
mle(normalF, start = list(mu = 10.44, sigma = 0.75))
```

```{r}
library("exptest")
pietra.exp.test(income, nrepl = 5000)
x = income
theta = NULL
for (i in 1:200) {
  xi = x[-i]
  theta = c(theta, log(mean(xi)))
}
jaceknife_se = sqrt(199*sum((theta - mean(theta))^2)/200);jaceknife_se
```

```{r}

```



